apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qfr4qdi6k-go 
  janus-idp.io/tekton: qfr4qdi6k-go
  backstage.io/kubernetes-id: qfr4qdi6k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qfr4qdi6k-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  